Sync with upstream (#18)
* Add TLPWhereGenerator interface

* Add generic TLPWhere oracle

* Implement TLPWhereGenerator interfaces for SQLite3

* Use generic TLPWhere oracle for SQLite3

* [Databend] Refactor tests

* [Databend] Update to v1.2.542

* Remove duplicated logs in NoREC oracle (#953)

* [ClickHouse] Added pattern for changed error message (#955)

* [ClickHouse] Added pattern for changed error message

https://fiddle.clickhouse.com/a3a95024-4da7-4275-baff-86f116014744

```
Received exception from server (version 24.2.3):
Code: 403. DB::Exception: Received from localhost:9000. DB::Exception: Cannot get JOIN keys from JOIN ON section: '476505718 = `_--right_2.c0`', found keys: [Left keys: [] Right keys [] Condition columns: '', 'equals(476505718, _--right_2.c0)']. (INVALID_JOIN_ON_EXPRESSION)
(query: SELECT SUM(check <> 0) FROM ((SELECT right_0.c0 AS `check` FROM t0 AS left FULL OUTER JOIN t0 AS right_0 ON ((left.c0)=(right_0.c0)) LEFT OUTER JOIN t0 AS right_1 ON ((left.c0)=(right_1.c0)) LEFT ANTI JOIN t0 AS right_2 ON ((476505718)=(right_2.c0)))) as res;)
```

* formatter

* Avoid storage parameters during CREATE TABLE for partitioned tables (#956)

CREATE TABLE WITH() allows storage parameters, but partitioned tables
emit an error (given below) if attempted. This is because partitioned
non-leaf tables are virutal tables [1] and don't accept
storage parameters.

Sample Error:
"ERROR: cannot specify storage parameters for a partitioned table"

This patch skips storage parameter generation for partitioned tables.

Ref:
1. https://www.postgresql.org/docs/current/ddl-partitioning.html

* Review feedback

* Ensure INHERITS() only uses tables (not views)

In Postgres, CREATE TABLE INHERITS () throws an error when VIEWs are
provided, sample given below.

ERROR: inherited relation "pg_buffercache" is not a table or foreign table

Ref:
1. https://www.postgresql.org/docs/current/ddl-inherit.html

* Revert "Ensure INHERITS() only uses tables (not views)"

This reverts commit 0316c1c9c2fa2ad2a82977cfe2587faaba78cec8.

* Ensure INHERITS() only uses tables (not views)

In Postgres, CREATE TABLE INHERITS () throws an error when VIEWs are
provided, sample given below.

ERROR: inherited relation "pg_buffercache" is not a table or foreign table

Ref:
1. https://www.postgresql.org/docs/current/ddl-inherit.html

* Another fix

---------

Co-authored-by: malwaregarry <malwaregarry@gmail.com>
Co-authored-by: ming wei <43949290+malwaregarry@users.noreply.github.com>
Co-authored-by: Manuel Rigger <rigger@nus.edu.sg>
Co-authored-by: Ilya Yatsishin <2159081+qoega@users.noreply.github.com>
Co-authored-by: Robins <tharakan@gmail.com>